language: node_js

node_js:
- 'stable'

script:
  - npm run build
  
install:
  - npm i

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: './src'
  fqdn: 'kryptosrovnavac.cz'
  on:
    branch: master